# Generated by Django 5.0.1 on 2024-01-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_rename_receipe_description_receipe_product_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipe',
            new_name='Product',
        ),
    ]
