# Generated by Django 5.0.1 on 2024-01-24 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_product_user_alter_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='User',
        ),
    ]
