# Generated by Django 5.0.1 on 2024-01-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_rename_user_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='User',
            new_name='user',
        ),
    ]
